import mongoose from 'mongoose';

const bookingSchema = new mongoose.Schema(
  {
    reference: { type: String, unique: true }, // SGH-1092 style, generated by the server
    guest: {
      name: { type: String, required: true, trim: true },
      email: { type: String, required: true, trim: true, lowercase: true },
      phone: { type: String, required: true, trim: true },
      avatar: { type: String, trim: true },
    },
    // Snapshot of the room at booking time (so old bookings keep their data)
    room: {
      roomId: { type: mongoose.Schema.Types.ObjectId, ref: 'Room' },
      name: { type: String, required: true },
      type: { type: String },
      number: { type: String },
    },
    checkIn: { type: Date, required: true },
    checkOut: { type: Date, required: true },
    guestsCount: {
      adults: { type: Number, default: 1, min: 1 },
      children: { type: Number, default: 0, min: 0 },
    },
    amount: { type: Number, default: 0, min: 0 },
    paymentStatus: { type: String, default: 'Pending', trim: true }, // Paid in Full, Deposit Paid (50%), Refunded ...
    status: {
      type: String,
      enum: ['Pending', 'Confirmed', 'Checked In', 'Completed', 'Cancelled'],
      default: 'Pending',
    },
    requests: { type: String, trim: true },
  },
  { timestamps: true }
);

export default mongoose.model('Booking', bookingSchema);
